builds:
  - binary: secrethub-http-proxy
    main: ./cmd/secrethub-http-proxy/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386

archive:
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  replacements:
    darwin: macOS
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
