version: 2
build_common: &build
  steps:
    - checkout
    - run: make build
jobs:
  build_golang_1.11:
    <<: *build
    docker:
      - image: circleci/golang:1.11
  build_golang_1.12:
    <<: *build
    docker:
      - image: circleci/golang:1.12

workflows:
  version: 2
  build:
    jobs:
      - build_golang_1.11
      - build_golang_1.12
